# SPDX-License-Identifier: BSD-3-Clause
# Copyright Contributors to the Imath Project.

set(IMATH_VERSION_MAJOR 1)
set(IMATH_VERSION_MINOR 0)
set(IMATH_VERSION_PATCH 0)
set(IMATH_VERSION       ${IMATH_VERSION_MAJOR}.${IMATH_VERSION_MINOR}.${IMATH_VERSION_PATCH})
set(IMATH_VERSION_API   ${IMATH_VERSION_MAJOR}_${IMATH_VERSION_MINOR})
