# SPDX-License-Identifier: BSD-3-Clause
# Copyright Contributors to the Imath Project.

set(IMATH_VERSION_MAJOR 1)
set(IMATH_VERSION_MINOR 0)
set(IMATH_VERSION_PATCH 0)
set(IMATH_VERSION       ${IMATH_VERSION_MAJOR}.${IMATH_VERSION_MINOR}.${IMATH_VERSION_PATCH})
set(IMATH_VERSION_API   ${IMATH_VERSION_MAJOR}_${IMATH_VERSION_MINOR})
set(IMATH_SOCURRENT 25)
set(IMATH_SOREVISION 0)
set(IMATH_SOAGE 0)
math(EXPR IMATH_SOVERSION "${IMATH_SOCURRENT} - ${IMATH_SOAGE}")
set(IMATH_LIB_VERSION "${IMATH_SOVERSION}.${IMATH_SOAGE}.${IMATH_SOREVISION}")
message(STATUS "Configure Imath Version: ${IMATH_VERSION} Lib API: ${IMATH_LIB_VERSION}")
