# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) Contributors to the OpenEXR Project.

name: Sign Release

on:
  release:
    types: [created]

permissions:
  contents: write
  id-token: write
  repository-projects: write
  
jobs:
  sign-release:
    name: Sign & upload release artifacts
    runs-on: ubuntu-latest
    env:
       tarball: Imath-${{ github.ref_name }}.tar.gz

    steps:
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.3.0
        with:
          cosign-release: 'v2.2.2'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Create archive
        run: git archive --format=tar.gz -o ${{ env.tarball }} ${{ github.ref_name }}

      - name: Sign archive with Sigstore
        run: cosign sign-blob --yes ${{ env.tarball }} --bundle ${{ env.tarball }}-cosign.bundle

      - name: Upload release archive
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release upload ${{ github.ref_name }} ${{ env.tarball }} ${{ env.tarball }}-cosign.bundle

